services:

  booking-db:
    image: mysql:8.0
    container_name: booking-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingdb
    ports:
      - "3307:3306"
    networks:
      - hotel-network

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    networks:
      - hotel-network

  booking-service:
    build: ./booking-service-php
    ports:
      - "8084:80"
    depends_on:
      - booking-db  
    networks:
      - hotel-network
    volumes:
      - ./booking-service-php/src:/app

  billing-service:
    build: ./billing-service-java
    ports:
      - "8083:8083"
    networks:
      - hotel-network

  api-gateway:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway-java/src/main/resources/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - booking-service
      - billing-service
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge  