version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
    volumes:
      - nexus_data:/nexus-data
    networks:
      - nexus-network
    restart: unless-stopped

volumes:
  nexus_data:
    driver: local

networks:
  nexus-network:
    driver: bridge