apiVersion: v1
kind: Namespace
metadata:
  name: hotel-checkin-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
  namespace: hotel-checkin-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-db
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      containers:
      - name: booking-db
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "bookingdb"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: booking-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: booking-db-storage
        persistentVolumeClaim:
          claimName: booking-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: booking-db-service
  namespace: hotel-checkin-system
spec:
  selector:
    app: booking-db
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-db-pvc
  namespace: hotel-checkin-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
