apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: hotel-checkin-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: your-dockerhub-username/booking-service:latest
        env:
        - name: DB_HOST
          value: "booking-db-service"
        - name: DB_DATABASE
          value: "bookingdb"
        - name: APP_ENV
          value: "production"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: hotel-checkin-system
spec:
  selector:
    app: booking-service
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
