server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: booking-service
          uri: http://booking-service:8082
          predicates:
            - Path=/api/reservas/**
        - id: billing-service
          uri: http://billing-service:8083
          predicates:
            - Path=/api/billing/**